// What `ML` promises (P8-S03, 05 §6).
//
// Two jobs, because the two Verification rows want different things.
//
// **With no arguments** this is the ctest test `ml`: the feature-schema rules, the signature checks
// a model gets when it is opened, and the concurrency claim — 20 threads sharing one session, each
// with its own `Scratch`, must agree to the last bit with a single-threaded run of the same inputs.
// That is the property the whole design rests on, and it is checked here rather than asserted in a
// comment.
//
// **With `--dump <model> <inputs.txt> <outputs.txt>`** it is the C++ half of the parity row: it runs
// the inputs on 20 threads and writes what it got, for `tests/integration/test_ml.py` to compare
// against Python's `onnxruntime`. The inputs come from a file because the two halves have to be
// asking the same question, and numpy's generator is not reproducible from C++.
//
// The model itself is generated by `tests/tools/toy_model.py` — tracked as a script, because a
// binary in git is a thing nobody can read a diff of.

#include <atomic>
#include <cstdio>
#include <fstream>
#include <random>
#include <string>
#include <thread>
#include <vector>

#include "Core/Errors.hh"
#include "ML.hh"
#include "check.hh"

namespace {

    constexpr int kWorkers = 20;

    // ── the schema, which needs no model at all ──────────────────────────────
    void featureSchema() {
        const ML::Features schema({"pt", "eta", "phi", "mass"});
        CHECK_EQ(schema.size(), std::size_t{4});
        CHECK_EQ(schema.index("phi"), 2);
        CHECK_EQ(schema.index("nonsense"), -1);

        CHECK_THROWS(ML::Features(std::vector<std::string>{}), Core::Error);
        CHECK_THROWS(ML::Features({"pt", "pt"}), Core::Error);   // filled by name, so it must be one
        CHECK_THROWS(ML::Features({"pt", ""}), Core::Error);

        ML::Row row = schema.row();
        CHECK(!row.complete());
        // An unset feature is a zero that means "no signal", which is not what the caller meant.
        CHECK_THROWS(row.values(), Core::Error);

        row.set("pt", 12.5);
        row.set("eta", -1.5);
        row.set("phi", 0.25);
        CHECK(!row.complete());
        CHECK_THROWS(row.values(), Core::Error);
        row.set("mass", 0.14);
        CHECK(row.complete());

        const ML::Floats values = row.values();
        CHECK_EQ(values.size(), std::size_t{4});
        CHECK(std::abs(values[0] - 12.5f) < 1e-6f);
        CHECK(std::abs(values[3] - 0.14f) < 1e-6f);

        CHECK_THROWS(row.set("nosuchfeature", 1.0), Core::Error);
        // A NaN reaches the network as one and comes back as a plausible number.
        CHECK_THROWS(row.set("pt", std::nan("")), Core::Error);
        CHECK_THROWS(row.set("pt", std::numeric_limits<double>::infinity()), Core::Error);

        row.clear();
        CHECK(!row.complete());
    }

#if defined(HEKIT_WITH_ONNX)

    std::vector<float> inputsFor(int rows, int width, unsigned seed) {
        std::mt19937 generator(seed);
        std::normal_distribution<float> spread(0.0f, 1.5f);
        std::vector<float> values(static_cast<std::size_t>(rows) * width);
        for (float& value : values) value = spread(generator);
        return values;
    }

    // ── what a model says about itself, checked when it is opened ────────────
    void modelSignature(const std::string& path) {
        const ML::OnnxModel model(path);
        CHECK_EQ(model.features(), std::size_t{4});
        CHECK_EQ(model.outputs(), std::size_t{2});
        CHECK_EQ(model.inputSignature().name, std::string("features"));
        CHECK_EQ(model.outputSignature().name, std::string("score"));
        CHECK_EQ(model.sha256().size(), std::size_t{64});
        CHECK(model.describe().find("features") != std::string::npos);

        // The batch is dynamic and says so; the width is not.
        CHECK_EQ(model.inputSignature().dims.size(), std::size_t{2});
        CHECK(model.inputSignature().dims[0] < 0);
        CHECK_EQ(model.inputSignature().dims[1], 4LL);

        // A schema that does not fit the model is caught once, at the start.
        ML::Features({"pt", "eta", "phi", "mass"}).matches(model);
        CHECK_THROWS(ML::Features({"pt", "eta"}).matches(model), Core::Error);

        // A name that does not match is a silent wrong answer otherwise.
        ML::Options named;
        named.input = "features";
        named.output = "score";
        const ML::OnnxModel checked(path, named);
        CHECK_EQ(checked.features(), std::size_t{4});

        ML::Options wrong;
        wrong.input = "inputs_renamed_since_training";
        CHECK_THROWS(ML::OnnxModel(path, wrong), Core::Error);

        CHECK_THROWS(ML::OnnxModel("/nonexistent/model.onnx"), Core::Error);
    }

    // ── one row, several rows, and a width that is not a multiple ────────────
    void batching(const std::string& path) {
        const ML::OnnxModel model(path);
        ML::Scratch scratch;

        const std::vector<float> one = inputsFor(1, 4, 11);
        const ML::Floats single = model.run(ML::Floats(one), scratch);
        CHECK_EQ(single.size(), std::size_t{2});
        // The toy ends in a sigmoid, so every output is a probability.
        for (const float value : single) CHECK(value > 0.0f && value < 1.0f);

        const std::vector<float> many = inputsFor(7, 4, 12);
        const ML::Floats batch = model.run(ML::Floats(many), scratch);
        CHECK_EQ(batch.size(), std::size_t{14});

        // A batch is the same as the rows run one at a time — which is what makes it a batch and
        // not a different model.
        std::vector<float> separately;
        ML::Scratch other;
        for (int row = 0; row < 7; ++row) {
            const ML::Floats got =
                model.run(ML::Floats(many.data() + row * 4, 4), other);
            separately.insert(separately.end(), got.begin(), got.end());
        }
        const std::vector<float> together(batch.begin(), batch.end());
        CHECK_EQ(separately.size(), together.size());
        for (std::size_t at = 0; at < separately.size(); ++at)
            CHECK(std::abs(separately[at] - together[at]) < 1e-6f);

        CHECK_THROWS(model.run(ML::Floats(one.data(), 3), scratch), Core::Error);
        CHECK_THROWS(model.run(ML::Floats{}, scratch), Core::Error);
    }

    /// Run `rows` of input on `kWorkers` threads, each with its own `Scratch`. The whole design in
    /// one function: one session, no locks, per-worker buffers.
    std::vector<float> runSharded(const ML::OnnxModel& model, const std::vector<float>& values,
                                  int rows, int width, int workers) {
        std::vector<float> got(static_cast<std::size_t>(rows) * model.outputs(), 0.0f);
        std::atomic<int> next{0};
        std::atomic<bool> failed{false};
        std::vector<std::thread> pool;
        for (int worker = 0; worker < workers; ++worker) {
            pool.emplace_back([&]() {
                ML::Scratch scratch;          // this worker's, and nothing else's
                try {
                    for (int row = next++; row < rows; row = next++) {
                        const ML::Floats out = model.run(
                            ML::Floats(values.data() + static_cast<std::size_t>(row) * width,
                                       static_cast<std::size_t>(width)),
                            scratch);
                        for (std::size_t at = 0; at < out.size(); ++at)
                            got[static_cast<std::size_t>(row) * model.outputs() + at] = out[at];
                    }
                } catch (...) {
                    failed = true;
                }
            });
        }
        for (std::thread& thread : pool) thread.join();
        CHECK(!failed);
        return got;
    }

    // ── the concurrency claim, as a number ───────────────────────────────────
    void twentyWorkersAgree(const std::string& path) {
        const ML::OnnxModel model(path);
        const int rows = 500;
        const std::vector<float> values = inputsFor(rows, 4, 2026);

        ML::Scratch alone;
        std::vector<float> serial;
        for (int row = 0; row < rows; ++row) {
            const ML::Floats out = model.run(ML::Floats(values.data() + row * 4, 4), alone);
            serial.insert(serial.end(), out.begin(), out.end());
        }

        const std::vector<float> sharded = runSharded(model, values, rows, 4, kWorkers);
        CHECK_EQ(serial.size(), sharded.size());

        // **Bit-for-bit**, not "to a tolerance": the same weights and the same inputs go through the
        // same kernels, so a difference would mean two workers had shared a buffer.
        std::size_t different = 0;
        for (std::size_t at = 0; at < serial.size(); ++at)
            if (serial[at] != sharded[at]) different += 1;
        CHECK_EQ(different, std::size_t{0});

        // And the model really is doing something: the outputs are not all one value.
        float lowest = serial.front();
        float highest = serial.front();
        for (const float value : serial) {
            lowest = std::min(lowest, value);
            highest = std::max(highest, value);
        }
        CHECK(highest - lowest > 0.1f);
    }

    // ── the C++ half of the parity row ───────────────────────────────────────
    int dump(const std::string& model_path, const std::string& inputs_path,
             const std::string& out_path) {
        const ML::OnnxModel model(model_path);
        std::ifstream reading(inputs_path);
        if (!reading) {
            std::fprintf(stderr, "cannot read %s\n", inputs_path.c_str());
            return 1;
        }
        std::vector<float> values;
        double value = 0.0;
        while (reading >> value) values.push_back(static_cast<float>(value));
        if (values.empty() || values.size() % model.features() != 0) {
            std::fprintf(stderr, "%s holds %zu floats, not a multiple of %zu\n",
                         inputs_path.c_str(), values.size(), model.features());
            return 1;
        }
        const int rows = static_cast<int>(values.size() / model.features());
        const std::vector<float> got =
            runSharded(model, values, rows, static_cast<int>(model.features()), kWorkers);

        std::ofstream writing(out_path);
        writing.precision(9);
        for (int row = 0; row < rows; ++row) {
            for (std::size_t at = 0; at < model.outputs(); ++at)
                writing << (at == 0 ? "" : " ")
                        << got[static_cast<std::size_t>(row) * model.outputs() + at];
            writing << "\n";
        }
        return writing ? 0 : 1;
    }

#endif  // HEKIT_WITH_ONNX

}  // namespace

int main(int argc, char** argv) {
#if defined(HEKIT_WITH_ONNX)
    if (argc >= 2 && std::string(argv[1]) == "--dump") {
        if (argc != 5) {
            std::fprintf(stderr, "usage: %s --dump <model.onnx> <inputs.txt> <outputs.txt>\n",
                         argv[0]);
            return 2;
        }
        try {
            return dump(argv[2], argv[3], argv[4]);
        } catch (const Core::Error& error) {
            std::fprintf(stderr, "%s\n", error.what());
            return 1;
        }
    }
#else
    (void)argc;
    (void)argv;
#endif

    featureSchema();

#if defined(HEKIT_WITH_ONNX)
#if defined(HEKIT_TOY_MODEL)
    const std::string model = HEKIT_TOY_MODEL;
    modelSignature(model);
    batching(model);
    twentyWorkersAgree(model);
#else
    std::fprintf(stderr, "NOTE: no toy model was generated; the inference checks were skipped\n");
#endif
#else
    std::fprintf(stderr, "NOTE: built without ONNX Runtime; only the feature schema was checked\n");
#endif
    return check::finish("ml");
}
