"""The parity row: `ML::OnnxModel` on 20 workers against Python's onnxruntime (P8-S03, 05 §6).

The claim being checked is narrow and worth stating plainly: **sharing one session across workers
does not change the answer**. So the same toy model and the same inputs go through

  * C++ — one `Ort::Session`, 20 threads pulling rows off a counter, each with its own `ML::Scratch`;
  * Python — `onnxruntime.InferenceSession`, one thread, which is the reference every other project
    would compare against.

and the two must agree **exactly** — all 1000 output floats bit-identical, not "to a tolerance".
That is a stronger claim than it first looks, and it is only true because both sides pin
`intra_op_num_threads = 1`: the same kernels then sum in the same order on the same weights, and
there is nothing left for a difference to come from. A threading bug — two workers sharing a buffer,
a scratch resized under another thread's feet — moves numbers far more than a last-bit, so a
tolerance loose enough to be safe against a future kernel change would also be loose enough to hide
the thing this row exists to catch. The assertion reports the largest disagreement when it fails, so
an ONNX Runtime upgrade that legitimately changes a kernel will say so rather than just going red.

The model is generated by `tests/tools/toy_model.py` rather than committed, so this test also
proves that script still produces something both runtimes can read.

Registered as the ctest test `ml_parity`.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tests" / "tools"))

INFER = REPO / "build" / "bin" / "test_ml"
RUN = REPO / "build" / "bin" / "hep-run"
MODULE = REPO / "build" / "modules" / "Examples" / "libhekit_ToyJets.so"
BASE_CARD = REPO / "tests" / "golden" / "inputs" / "PhotoProduction" / "photo_ep.cmnd"
SCRATCH = REPO / "output" / "scratch"
ROWS = 500

np = pytest.importorskip("numpy")
pytest.importorskip("onnx")
pytest.importorskip("onnxruntime")

pytestmark = [
    pytest.mark.skipif(not INFER.is_file(), reason="build test_ml first (cmake --build build)"),
]


@pytest.fixture(scope="module")
def both(tmp_path_factory):
    """The same inputs through both runtimes."""
    import toy_model

    root = tmp_path_factory.mktemp("ml")
    model = toy_model.build(root / "toy.onnx")

    values = toy_model.sample_inputs(ROWS)
    inputs = root / "inputs.txt"
    inputs.write_text("\n".join(" ".join(f"{value:.9g}" for value in row) for row in values),
                      encoding="utf-8")

    outputs = root / "outputs.txt"
    done = subprocess.run([str(INFER), "--dump", str(model), str(inputs), str(outputs)],
                          capture_output=True, text=True, encoding="utf-8", errors="replace",
                          timeout=600)
    assert done.returncode == 0, done.stderr[-3000:]

    from_cxx = np.loadtxt(outputs, dtype="float32").reshape(ROWS, -1)
    from_python = toy_model.reference(model, values)
    return from_cxx, from_python, model


def test_the_shapes_match(both):
    from_cxx, from_python, _ = both
    assert from_cxx.shape == from_python.shape == (ROWS, 2)


def test_twenty_workers_agree_with_python(both):
    """The row itself. One session, 20 threads, no locks — and bit-identical numbers."""
    from_cxx, from_python, _ = both
    largest = float(np.max(np.abs(from_cxx - from_python)))
    assert np.array_equal(from_cxx, from_python), (
        f"largest disagreement {largest:.3g} over {ROWS} rows x 2 outputs")


def test_the_model_actually_discriminates(both):
    """A model that returned a constant would pass the row above and mean nothing."""
    _, from_python, _ = both
    assert float(np.ptp(from_python)) > 0.5, "the toy model's outputs barely vary"


def test_a_rerun_gives_the_same_numbers(both, tmp_path):
    """Deterministic across processes: the thread that happened to take a row does not matter."""
    from_cxx, _, model = both

    values = __import__("toy_model").sample_inputs(ROWS)
    inputs = tmp_path / "inputs.txt"
    inputs.write_text("\n".join(" ".join(f"{value:.9g}" for value in row) for row in values),
                      encoding="utf-8")
    outputs = tmp_path / "again.txt"
    done = subprocess.run([str(INFER), "--dump", str(model), str(inputs), str(outputs)],
                          capture_output=True, text=True, encoding="utf-8", errors="replace",
                          timeout=600)
    assert done.returncode == 0, done.stderr[-3000:]
    again = np.loadtxt(outputs, dtype="float32").reshape(ROWS, -1)
    assert np.array_equal(from_cxx, again), "two 20-worker runs disagreed with each other"


def test_a_bad_input_file_is_refused(tmp_path, both):
    """A width that is not a multiple of the model's is a message, not a reshaped tensor."""
    _, _, model = both
    inputs = tmp_path / "ragged.txt"
    inputs.write_text("1.0 2.0 3.0\n", encoding="utf-8")     # three floats into a four-wide model
    done = subprocess.run([str(INFER), "--dump", str(model), str(inputs), str(tmp_path / "o.txt")],
                          capture_output=True, text=True, encoding="utf-8", errors="replace",
                          timeout=600)
    assert done.returncode != 0
    assert "not a multiple of 4" in done.stderr


# ── the step's Goal, end to end ──────────────────────────────────────────────
# The rows above prove `ML::OnnxModel` is right. This proves a **module** can use it: the same
# `ToyJets` the module tests measure, given `model = "..."`, scores every jet it clusters and the
# score lands in the same `analysis.yoda` as everything else.

@pytest.mark.slow
@pytest.mark.skipif(not RUN.is_file() or not MODULE.is_file(),
                    reason="build hep-run and the toy module first")
def test_a_module_scores_its_jets(tmp_path):
    import json
    import toy_model

    yoda = pytest.importorskip("yoda")
    tomli_w = pytest.importorskip("tomli_w")

    model = toy_model.build(tmp_path / "toy.onnx")
    cards = tmp_path / "cards"
    cards.mkdir(parents=True)
    (cards / "photo_ep.cmnd").write_bytes(BASE_CARD.read_bytes())
    (cards / "point.cmnd").write_text(
        "Beams:frameType = 2\nBeams:eA = 920\nBeams:eB = 27.5\nBeams:idB = -11\n"
        "PDF:pSet = LHAPDF6:MSTW2008lo68cl\n", encoding="utf-8")

    spec = {
        "meta": {"schema": 2, "point": "ml", "hash": "sha256:" + "ab" * 32,
                 "origin": "P8-S03", "aliases": []},
        "run": {"events": 300, "threads": 2, "mode": "auto", "seed": 606001,
                "seeds": {"point": 606001, "instances": [606001, 606002]}},
        "source": {"kind": "pythia",
                   "cards": [str(cards / "photo_ep.cmnd"), str(cards / "point.cmnd")]},
        "output": {"dir": str(tmp_path), "yoda": "analysis.yoda",
                   "summary": "run.summary.json"},
        "sink": [{"kind": "module", "name": "ToyJets",
                  "paths": [str(MODULE.parent)],
                  "options": {"pt_min": 0.5, "eta_max": 5.0, "model": str(model)}}],
        "status": {"fd": 3, "heartbeat_ms": 500},
    }
    path = tmp_path / "run.toml"
    path.write_text(tomli_w.dumps(spec), encoding="utf-8")
    SCRATCH.mkdir(parents=True, exist_ok=True)
    done = subprocess.run([str(RUN), str(path)], capture_output=True, text=True,
                          encoding="utf-8", errors="replace", timeout=1800, cwd=SCRATCH)
    assert done.returncode == 0, done.stderr[-3000:]

    objects = yoda.read(str(tmp_path / "analysis.yoda"))
    assert "/ToyJets/score" in objects, sorted(objects)
    score = objects["/ToyJets/score"]
    assert score.sumW() > 0, "the module booked a score histogram and never filled it"

    # The toy ends in a sigmoid, so every entry is in [0, 1] — and the histogram's range is [0, 1],
    # so anything outside it would have gone to an overflow rather than shown up here.
    whole = json.loads((tmp_path / "run.summary.json").read_text(encoding="utf-8"))
    assert whole["run"]["events"] == 300

    # Which weights answered, in the summary (05 §6). A hash nothing writes down is no better than
    # no hash, and "we used the same model" is the commonest unverifiable claim there is.
    import hashlib
    inputs = whole["inputs"]
    assert inputs["ToyJets.model"] == str(model)
    assert inputs["ToyJets.model_sha256"] == hashlib.sha256(model.read_bytes()).hexdigest()


@pytest.mark.skipif(not RUN.is_file() or not MODULE.is_file(),
                    reason="build hep-run and the toy module first")
def test_a_missing_model_is_caught_by_the_preflight(tmp_path):
    """A typo in the model path costs a second, not a generation (06 §3.3)."""
    tomli_w = pytest.importorskip("tomli_w")

    cards = tmp_path / "cards"
    cards.mkdir(parents=True)
    (cards / "photo_ep.cmnd").write_bytes(BASE_CARD.read_bytes())
    (cards / "point.cmnd").write_text(
        "Beams:frameType = 2\nBeams:eA = 920\nBeams:eB = 27.5\nBeams:idB = -11\n"
        "PDF:pSet = LHAPDF6:MSTW2008lo68cl\n", encoding="utf-8")

    spec = {
        "meta": {"schema": 2, "point": "ml", "hash": "sha256:" + "ab" * 32,
                 "origin": "P8-S03", "aliases": []},
        "run": {"events": 10, "threads": 1, "mode": "serial", "seed": 606001,
                "seeds": {"point": 606001, "instances": [606001]}},
        "source": {"kind": "pythia",
                   "cards": [str(cards / "photo_ep.cmnd"), str(cards / "point.cmnd")]},
        "output": {"dir": str(tmp_path), "yoda": "analysis.yoda",
                   "summary": "run.summary.json"},
        "sink": [{"kind": "module", "name": "ToyJets", "paths": [str(MODULE.parent)],
                  "options": {"model": str(tmp_path / "no-such-model.onnx")}}],
        "status": {"fd": 3, "heartbeat_ms": 500},
    }
    path = tmp_path / "run.toml"
    path.write_text(tomli_w.dumps(spec), encoding="utf-8")
    SCRATCH.mkdir(parents=True, exist_ok=True)
    done = subprocess.run([str(RUN), str(path), "--check"], capture_output=True, text=True,
                          encoding="utf-8", errors="replace", timeout=600, cwd=SCRATCH)
    assert done.returncode != 0
    assert "no ONNX model at" in done.stderr
