[events]
event_count = 1_000_000

[pythia]
cmnd_file = "eic_5x41.cmnd"

[rivpyth]
project = "PhotoProduction"
generator = "generator.exe"
analysis = "photo_5x41"
hepmc_file = "eic_28.hepmc"
yoda_file="eic28.yoda"
plugin_dir = "."
threads = 20
path_literal = false