
[events]
event_count = 1_000_000

[pythia]
cmnd_file = "eic_10x100.cmnd"

[rivpyth]
project = "PhotoProduction"
generator = "generator.exe"
analysis = "photo_10x100"
hepmc_file = "eic_63.hepmc"
yoda_file="eic63.yoda"
plugin_dir = "."
threads = 20
path_literal = false