"""The configuration reference, generated from the schema (03 §6).

Documentation that is generated cannot drift from behaviour: every row below is the same `Field` the
loader validates against. This replaces the hand-maintained `configs/all.toml` and `configs/templates/`
of the old stack (archived in `legacy/configs/`).
"""

from __future__ import annotations

from typing import Any

from . import schema as sch
from .fields import Field, Section

TITLE = "Configuration reference (schema 2)"
INTRO = """\
Generated by `hep config reference` from the field tables in `hekit.config.schema`; do not edit by hand.
Each section is one TOML table unless it says otherwise. The design behind it is
[03_Configuration.md](../03_Configuration.md).
"""


def _row(name: str, spec: Field) -> str:
    default = "—" if spec.default_value() in (None, "", [], {}) else f"`{spec.default_value()!r}`"
    return f"| `{name}` | {spec.describe()} | {default} | {spec.doc} |"


def _section(section: Section, heading: str, note: str = "") -> list[str]:
    lines = [f"### {heading}", ""]
    if section.doc:
        lines += [section.doc, ""]
    if note:
        lines += [note, ""]
    lines += ["| Key | Type | Default | Meaning |", "|---|---|---|---|"]
    lines += [_row(name, spec) for name, spec in section.fields.items()]
    lines.append("")
    for name, subsection in section.subsections.items():
        lines += _section(subsection, f"`[{section.name}.{name}]`")
    return lines


SHAPE_NOTE = {
    "array": "Written as an array of tables: repeat `[[{name}]]` once per entry.",
    "named": "Written as one table per name: `[{name}.<name>]`.",
}


def markdown() -> str:
    """The whole reference, deterministically ordered."""
    lines = [f"# {TITLE}", "", INTRO, "## Top level", "",
             "| Key | Type | Default | Meaning |", "|---|---|---|---|"]
    lines += [_row(name, spec) for name, spec in sch.TOP_LEVEL.items()]
    lines += ["", "## Sections", ""]
    for name, section in sch.SECTIONS.items():
        note = SHAPE_NOTE.get(section.shape, "").format(name=name)
        if section.machine_keys:
            allowed = ", ".join(f"`{key}`" for key in section.machine_keys)
            note = (note + " " if note else "") + \
                f"A machine file (`~/.config/hekit/machine.toml`) may set {allowed}."
        lines += _section(section, f"`[{name}]`", note)
    lines += ["## Values a machine file may set", "",
              "Only these, so that a machine can tune performance without changing physics (03 §2):", ""]
    lines += [f"- `{name}.{key}`" for name in sch.MACHINE_SECTIONS
              for key in sch.SECTIONS[name].machine_keys]
    lines.append("")
    return "\n".join(lines)


STARTER = '''\
# {project}/run.toml — written by `hep config init {project}`.
# Every key is documented in docs/rework/reference/config.md (`hep config reference`).

schema = 2

[run]
name    = "{project_lower}"     # output stem and the prefix of every point name
events  = 10_000
seed    = 270403                # base of the identity seed policy; never offset by position
threads = 0                     # 0 = all cores

[generator]
tool = "pythia"
card = "base.cmnd"              # the native card, next to this file

[beams]
ids      = [2212, 11]           # PDG ids [A, B]
energies = [275, 18]            # GeV, lab frame; a single number is √s in the CM frame

[rivet]
# Fill this in before running: a config with no analysis, module analyzer or event store has nothing to
# consume the events, and `hep plan` will say so.
analyses = []                   # e.g. ["{project_lower}_analysis"]
paths    = ["analyses/{project}"]

[plot]
legends = "label"

# A quantity is something you can scan, pin or leave at a default.
# [quantity.pdf]
# type   = "setting"
# key    = "PDF:pSet"
# values = ["LHAPDF6:MSTW2008lo68cl", "LHAPDF6:NNPDF23_lo_as_0130_qed"]
# labels = ["MSTW 2008 LO", "NNPDF 2.3 LO"]
# tags   = ["MSTW08lo", "NNPDF23lo"]
# use    = 1

[sweep]
across = []                     # e.g. ["pdf"], or ["energies+beams", "pdf"] for a coupled grid

# [study.pdf]
# description = "PDF comparison"
# across      = ["pdf"]
'''


def starter(project: str) -> str:
    """A commented starter file for a new project (`hep config init`)."""
    return STARTER.format(project=project, project_lower=project.lower())
