[run]
serial = 1
sr_Padding = 2
event_count = 10000
beam_energy = 7000 #GeV

[logging]
bin_count = 500
hist_scaling = 1.0

print_interval = 50 #events
check_interval = 100_000 #events

heartbeat_interval = 2000 #milliseconds
terminal_refresh_interval = 2 #minutes
program_stall_threshold = 5 #minutes

[paths]
# paths to save root and log file
# directory = "output/Lambda_Data/"
output_log_directory = "logs/"
checkpoint_directory = "checkpoints/"

serialDirectory = true                                      # directory/_{serial} is made  mainDirectory
logInSubDir = true                                          # if true, output_logdirectory is subdirectory in mainDirectory
checkpointsInSubDir = true 

[file]
# file name parameters
prefix = "Lambda_Recons"
serial = false
energy = true
events = true

[lambda]
hist_limits = "Lambda_Limits"
delta_mass_gev = 0.15 #GeV
delta_theta_rad = 0.1 #radians

