[events]
nThreads   = 0   # 0 = auto (hardware_concurrency - 2)
input_file = "output/Lambda_Reconstruction/_1/Lambda_Gen_7000GeV_10k.root"

[record]
serial     = 1
sr_padding = 2

[paths]
directory            = "output/Lambda_Reconstruction/"
output_log_directory = "logs/"
checkpoint_directory = "checkpoints/"
serialDirectory      = true
logInSubDir          = true
checkpointsInSubDir  = true

[file]
prefix = "Lambda_Recons"
serial = false
energy = false
events = false

[lambda]
hist_limits     = "Lambda_Limits"
delta_mass_gev  = 0.15
delta_theta_rad = 0.1

[metadata]
dataset_name = "Lambda_MC_pp"
data_type    = "MC"
run_period   = ""
campaign     = ""
notes        = ""
